site_name: iceoryx.io
site_url: https://iceoryx.io
repo_url: https://github.com/eclipse/iceoryx
edit_uri: ""
docs_dir: doc/website/
remote_branch: main
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - toc:
      permalink: ðŸ”—
  - meta
  - markdown_include.include
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - awesome-pages
  - search
  - autolinks
theme:
  name: 'material'
  custom_dir: doc/website/overrides
  font: false
  logo: images/iceoryx-logo-white.png
  favicon: images/favicon.ico
  features:
    - navigation.indexes
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
use_directory_urls: true
