# This is a basic workflow to help you get started with Actions

name: Colcon build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-20.04]

    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.23
        with:
          required-ros-distributions: foxy
      - name: Install Iceoryx Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y cmake libacl1-dev libncurses5-dev pkg-config
          mkdir -p src/iceoryx
          cd $GITHUB_WORKSPACE/src/iceoryx

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check copyrights
        run: |
          source /opt/ros/foxy/setup.bash
          cd $GITHUB_WORKSPACE
          ament_copyright --exclude LICENSE CONTRIBUTING.md

      - name: Build & Test
        run: |
          cd $GITHUB_WORKSPACE
          colcon build
